on:
  push:
  pull_request:

jobs:

  test:
    uses: ConorMacBride/github-actions-workflows/.github/workflows/publish.yml@initial-tox
    with:
      posargs: --openmp-expected=True
      coverage: codecov
      envs: |
        # Code style
        - linux: style
        # Docs
        - linux: build_docs
        # Standard tests
        - linux: py36-test-oldestdeps
        - linux: py37-test
        - linux: py38-test
        - linux: py38-test-dev
        - macos: py38-test-dev
          posargs: --openmp-expected=False
        - windows: py36-test
        - windows: py38-test-dev
        # Test with more compilers, for the OpenMP helpers
        - macos: py38-test-osxclang-conda
        - linux: py38-test-linuxgcc-conda
        # Test downstream packages
        - linux: py39-downstream

  publish:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@main
    with:
      test_extras: test
      test_command: pytest --pyargs extension_helpers
    secrets:
      pypi_password: ${{ secrets.pypi_password }}
